In [1]:
import pandas as pd
import numpy as np

In [86]:
tmp_df = pd.DataFrame(index = range(0,3), columns=['a'])

In [109]:
tmp_df.a = [1,0,2]

In [110]:
tmp_df

a
0  1
1  0
2  2

In [112]:
tmp_count = tmp_df.a.value_counts()

In [2]:
items = pd.read_csv('items.csv')

In [3]:
items

Unnamed: 0  baseball  economics  politics  Europe  Asia  soccer  war  \
0        doc1         1          0         1       0     1       1    0   
1        doc2         0          1         1       1     0       0    0   
2        doc3         0          0         0       1     1       1    0   
3        doc4         0          0         1       1     0       0    1   
4        doc5         0          1         0       0     0       0    0   
5        doc6         1          0         0       1     0       0    0   
6        doc7         0          0         0       0     0       0    0   
7        doc8         0          0         1       1     0       0    1   
8        doc9         0          0         0       0     0       1    0   
9       doc10         0          1         0       0     1       0    1   
10      doc11         0          0         1       0     1       0    0   
11      doc12         1          0         0       0     0       1    1   
12      doc13         0          0         1       1     1       0    0   
13      doc14         0          1         1       1     0       0    0   
14      doc15         0          0         0       1     0       1    1   
15      doc16         1          0         0       0     0       1    0   
16      doc17         0          1         1       1     0       0    0   
17      doc18         0          0         0       1     0       0    0   
18      doc19         0          1         1       0     1       0    1   
19      doc20         0          0         1       1     0       0    1   

    security  shopping  family  
0          0         0       1  
1          1         0       0  
2          0         0       0  
3          1         0       0  
4          0         1       1  
5          0         0       0  
6          1         0       1  
7          0         0       1  
8          0         1       0  
9          0         0       0  
10         0         1       0  
11         0         0       0  
12         1         0       0  
13         0         1       0  
14         1         0       0  
15         0         1       0  
16         1         0       0  
17         0         1       0  
18         0         0       1  
19         0         1       0

In [4]:
users = pd.read_csv('users.csv')

In [5]:
users

Unnamed: 0  User 1  User 2
0        doc1     1.0    -1.0
1        doc2    -1.0     1.0
2        doc3     NaN     NaN
3        doc4     NaN     1.0
4        doc5     NaN     NaN
5        doc6     1.0     NaN
6        doc7     NaN     NaN
7        doc8     NaN     NaN
8        doc9     NaN     NaN
9       doc10     NaN     NaN
10      doc11     NaN     NaN
11      doc12     NaN    -1.0
12      doc13     NaN     NaN
13      doc14     NaN     NaN
14      doc15     NaN     NaN
15      doc16     1.0     NaN
16      doc17     NaN     1.0
17      doc18     NaN     NaN
18      doc19    -1.0     NaN
19      doc20     NaN     NaN

# 단어별 연관성 계산

In [6]:
items_col = list(items.columns)

In [7]:
users_pro = pd.DataFrame(index=[0,1], columns=items_col)
users_pro['Unnamed: 0'] = ['User 1', 'User 2']
users_pro

Unnamed: 0 baseball economics politics Europe Asia soccer  war security  \
0     User 1      NaN       NaN      NaN    NaN  NaN    NaN  NaN      NaN   
1     User 2      NaN       NaN      NaN    NaN  NaN    NaN  NaN      NaN   

  shopping family  
0      NaN    NaN  
1      NaN    NaN

In [48]:
items.baseball

0     1
1     0
2     0
3     0
4     0
5     1
6     0
7     0
8     0
9     0
10    0
11    1
12    0
13    0
14    0
15    1
16    0
17    0
18    0
19    0
Name: baseball, dtype: int64

In [49]:
users['User 1']

0     1.0
1    -1.0
2     NaN
3     NaN
4     NaN
5     1.0
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    1.0
16    NaN
17    NaN
18   -1.0
19    NaN
Name: User 1, dtype: float64

In [53]:
np.array(items.baseball)

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int64)

In [60]:
np.array(users['User 1'])

array([ 1., -1., nan, nan, nan,  1., nan, nan, nan, nan, nan, nan, nan,
       nan, nan,  1., nan, nan, -1., nan])

In [63]:
list(items.columns)

['Unnamed: 0',
 'baseball',
 'economics',
 'politics',
 'Europe',
 'Asia',
 'soccer',
 'war',
 'security',
 'shopping',
 'family']

In [67]:
np.array([1,2,3])*np.array([[1,2,3],[1,2,3]])

array([[1, 4, 9],
       [1, 4, 9]])

In [8]:
keyword = items_col[1:]
for i in keyword:
    tmp_list = list()
    tmp_list.append(np.nansum(np.array(items[i])*np.array(users['User 1'])))
    tmp_list.append(np.nansum(np.array(items[i])*np.array(users['User 2'])))
    users_pro[i] = tmp_list

In [9]:
users_pro

Unnamed: 0  baseball  economics  politics  Europe  Asia  soccer  war  \
0     User 1       3.0       -2.0      -1.0     0.0   0.0     2.0 -1.0   
1     User 2      -2.0        2.0       2.0     3.0  -1.0    -2.0  0.0   

   security  shopping  family  
0      -1.0       1.0     0.0  
1       3.0       0.0    -1.0

# 1. 문서에 대한 예측 값(dot product)

In [10]:
users_doc_pro = pd.DataFrame(index=range(0,20), columns=['User 1', 'User 2'])

In [11]:
users_doc_pro

User 1 User 2
0     NaN    NaN
1     NaN    NaN
2     NaN    NaN
3     NaN    NaN
4     NaN    NaN
5     NaN    NaN
6     NaN    NaN
7     NaN    NaN
8     NaN    NaN
9     NaN    NaN
10    NaN    NaN
11    NaN    NaN
12    NaN    NaN
13    NaN    NaN
14    NaN    NaN
15    NaN    NaN
16    NaN    NaN
17    NaN    NaN
18    NaN    NaN
19    NaN    NaN

In [12]:
users_doc_pro['User 1'] = np.dot(items[keyword], users_pro[keyword][0:1].values[0])
users_doc_pro['User 2'] = np.dot(items[keyword], users_pro[keyword][1:2].values[0])
users_doc_pro['docs'] = users['Unnamed: 0']

In [13]:
users_doc_pro

User 1  User 2   docs
0      4.0    -4.0   doc1
1     -4.0    10.0   doc2
2      2.0     0.0   doc3
3     -3.0     8.0   doc4
4     -1.0     1.0   doc5
5      3.0     1.0   doc6
6     -1.0     2.0   doc7
7     -2.0     4.0   doc8
8      3.0    -2.0   doc9
9     -3.0     1.0  doc10
10     0.0     1.0  doc11
11     4.0    -4.0  doc12
12    -2.0     7.0  doc13
13    -2.0     7.0  doc14
14     0.0     4.0  doc15
15     6.0    -4.0  doc16
16    -4.0    10.0  doc17
17     1.0     3.0  doc18
18    -4.0     2.0  doc19
19    -1.0     5.0  doc20

In [69]:
users_doc_pro.sort_values(by=['User 1'], ascending=False)[:5]

User 1  User 2   docs
15     6.0    -4.0  doc16
0      4.0    -4.0   doc1
11     4.0    -4.0  doc12
8      3.0    -2.0   doc9
5      3.0     1.0   doc6

In [71]:
(users_doc_pro['User 2'] < 0).sum()

4

# 2. 가중치 적용

In [75]:
item_w = items[keyword]
item_w

baseball  economics  politics  Europe  Asia  soccer  war  security  \
0          1          0         1       0     1       1    0         0   
1          0          1         1       1     0       0    0         1   
2          0          0         0       1     1       1    0         0   
3          0          0         1       1     0       0    1         1   
4          0          1         0       0     0       0    0         0   
5          1          0         0       1     0       0    0         0   
6          0          0         0       0     0       0    0         1   
7          0          0         1       1     0       0    1         0   
8          0          0         0       0     0       1    0         0   
9          0          1         0       0     1       0    1         0   
10         0          0         1       0     1       0    0         0   
11         1          0         0       0     0       1    1         0   
12         0          0         1       1     1       0    0         1   
13         0          1         1       1     0       0    0         0   
14         0          0         0       1     0       1    1         1   
15         1          0         0       0     0       1    0         0   
16         0          1         1       1     0       0    0         1   
17         0          0         0       1     0       0    0         0   
18         0          1         1       0     1       0    1         0   
19         0          0         1       1     0       0    1         0   

    shopping  family  
0          0       1  
1          0       0  
2          0       0  
3          0       0  
4          1       1  
5          0       0  
6          0       1  
7          0       1  
8          1       0  
9          0       0  
10         1       0  
11         0       0  
12         0       0  
13         1       0  
14         0       0  
15         1       0  
16         0       0  
17         1       0  
18         0       1  
19         1       0

In [76]:
item_w.sum(axis=1)

0     5
1     4
2     3
3     4
4     3
5     2
6     2
7     4
8     2
9     3
10    3
11    3
12    4
13    4
14    4
15    3
16    4
17    2
18    5
19    4
dtype: int64

In [83]:
np.array(item_w.sum(axis=1)).reshape(20,1)

array([[5],
       [4],
       [3],
       [4],
       [3],
       [2],
       [2],
       [4],
       [2],
       [3],
       [3],
       [3],
       [4],
       [4],
       [4],
       [3],
       [4],
       [2],
       [5],
       [4]], dtype=int64)

In [18]:
weight_calc = np.array(item_w)/np.sqrt(np.array(item_w.sum(axis=1)).reshape(20,1))
weight_calc

array([[0.4472136 , 0.        , 0.4472136 , 0.        , 0.4472136 ,
        0.4472136 , 0.        , 0.        , 0.        , 0.4472136 ],
       [0.        , 0.5       , 0.5       , 0.5       , 0.        ,
        0.        , 0.        , 0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.57735027,
        0.57735027, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.5       , 0.        ,
        0.        , 0.5       , 0.5       , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.57735027],
       [0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.70710678],
       [0.        , 0.        , 0.5      

In [19]:
item_w = pd.DataFrame(data = weight_calc, columns=keyword)

In [20]:
item_w

baseball  economics  politics    Europe      Asia    soccer       war  \
0   0.447214   0.000000  0.447214  0.000000  0.447214  0.447214  0.000000   
1   0.000000   0.500000  0.500000  0.500000  0.000000  0.000000  0.000000   
2   0.000000   0.000000  0.000000  0.577350  0.577350  0.577350  0.000000   
3   0.000000   0.000000  0.500000  0.500000  0.000000  0.000000  0.500000   
4   0.000000   0.577350  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.707107   0.000000  0.000000  0.707107  0.000000  0.000000  0.000000   
6   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000   0.000000  0.500000  0.500000  0.000000  0.000000  0.500000   
8   0.000000   0.000000  0.000000  0.000000  0.000000  0.707107  0.000000   
9   0.000000   0.577350  0.000000  0.000000  0.577350  0.000000  0.577350   
10  0.000000   0.000000  0.577350  0.000000  0.577350  0.000000  0.000000   
11  0.577350   0.000000  0.000000  0.000000  0.000000  0.577350  0.577350   
12  0.000000   0.000000  0.500000  0.500000  0.500000  0.000000  0.000000   
13  0.000000   0.500000  0.500000  0.500000  0.000000  0.000000  0.000000   
14  0.000000   0.000000  0.000000  0.500000  0.000000  0.500000  0.500000   
15  0.577350   0.000000  0.000000  0.000000  0.000000  0.577350  0.000000   
16  0.000000   0.500000  0.500000  0.500000  0.000000  0.000000  0.000000   
17  0.000000   0.000000  0.000000  0.707107  0.000000  0.000000  0.000000   
18  0.000000   0.447214  0.447214  0.000000  0.447214  0.000000  0.447214   
19  0.000000   0.000000  0.500000  0.500000  0.000000  0.000000  0.500000   

    security  shopping    family  
0   0.000000  0.000000  0.447214  
1   0.500000  0.000000  0.000000  
2   0.000000  0.000000  0.000000  
3   0.500000  0.000000  0.000000  
4   0.000000  0.577350  0.577350  
5   0.000000  0.000000  0.000000  
6   0.707107  0.000000  0.707107  
7   0.000000  0.000000  0.500000  
8   0.000000  0.707107  0.000000  
9   0.000000  0.000000  0.000000  
10  0.000000  0.577350  0.000000  
11  0.000000  0.000000  0.000000  
12  0.500000  0.000000  0.000000  
13  0.000000  0.500000  0.000000  
14  0.500000  0.000000  0.000000  
15  0.000000  0.577350  0.000000  
16  0.500000  0.000000  0.000000  
17  0.000000  0.707107  0.000000  
18  0.000000  0.000000  0.447214  
19  0.000000  0.500000  0.000000

In [21]:
users_pro_w = pd.DataFrame(index=[0,1], columns=items_col)
users_pro_w['Unnamed: 0'] = ['User 1', 'User 2']
users_pro_w

Unnamed: 0 baseball economics politics Europe Asia soccer  war security  \
0     User 1      NaN       NaN      NaN    NaN  NaN    NaN  NaN      NaN   
1     User 2      NaN       NaN      NaN    NaN  NaN    NaN  NaN      NaN   

  shopping family  
0      NaN    NaN  
1      NaN    NaN

In [22]:
keyword = items_col[1:]
for i in keyword:
    tmp_list = list()
    tmp_list.append(np.nansum(np.array(item_w[i])*np.array(users['User 1'])))
    tmp_list.append(np.nansum(np.array(item_w[i])*np.array(users['User 2'])))
    users_pro_w[i] = tmp_list

In [23]:
users_pro_w

Unnamed: 0  baseball  economics  politics    Europe      Asia    soccer  \
0     User 1  1.731671  -0.947214 -0.500000  0.207107  0.000000  1.024564   
1     User 2 -1.024564   1.000000  1.052786  1.500000 -0.447214 -1.024564   

        war  security  shopping    family  
0 -0.447214      -0.5   0.57735  0.000000  
1 -0.077350       1.5   0.00000 -0.447214

In [24]:
users_doc_pro_w = pd.DataFrame(index=range(0,20), columns=['User 1', 'User 2'])
users_doc_pro_w

User 1 User 2
0     NaN    NaN
1     NaN    NaN
2     NaN    NaN
3     NaN    NaN
4     NaN    NaN
5     NaN    NaN
6     NaN    NaN
7     NaN    NaN
8     NaN    NaN
9     NaN    NaN
10    NaN    NaN
11    NaN    NaN
12    NaN    NaN
13    NaN    NaN
14    NaN    NaN
15    NaN    NaN
16    NaN    NaN
17    NaN    NaN
18    NaN    NaN
19    NaN    NaN

In [25]:
users_doc_pro_w['User 1'] = np.dot(item_w[keyword], users_pro_w[keyword][0:1].values[0])
users_doc_pro_w['User 2'] = np.dot(item_w[keyword], users_pro_w[keyword][1:2].values[0])
users_doc_pro_w['docs'] = users['Unnamed: 0']

In [26]:
users_doc_pro_w

User 1    User 2   docs
0   1.009019 -0.845577   doc1
1  -0.870053  2.526393   doc2
2   0.711105  0.016294   doc3
3  -0.620053  1.987718   doc4
4  -0.213541  0.319151   doc5
5   1.370923  0.336184   doc6
6  -0.353553  0.744432   doc7
7  -0.370053  1.014111   doc8
8   1.132724 -0.724476   doc9
9  -0.805073  0.274493  doc10
10  0.044658  0.349628  doc11
11  1.333114 -1.227723  doc12
12 -0.396447  1.802786  doc13
13 -0.331378  1.776393  doc14
14  0.142229  0.949043  doc15
15  1.924646 -1.183064  doc16
16 -0.870053  2.526393  doc17
17  0.554695  1.060660  doc18
18 -0.847214  0.483442  doc19
19 -0.081378  1.237718  doc20

In [27]:
## 비교를 위한 1번 문제의 결과 호출
users_doc_pro.sort_values(by=['User 1'], ascending=False)[:5]

User 1  User 2   docs
15     6.0    -4.0  doc16
0      4.0    -4.0   doc1
11     4.0    -4.0  doc12
8      3.0    -2.0   doc9
5      3.0     1.0   doc6

In [28]:
users_doc_pro_w.sort_values(by=['User 1'], ascending=False)[:5]

User 1    User 2   docs
15  1.924646 -1.183064  doc16
5   1.370923  0.336184   doc6
11  1.333114 -1.227723  doc12
8   1.132724 -0.724476   doc9
0   1.009019 -0.845577   doc1

# 3. IDF

In [29]:
item_for_idf = items[keyword]
item_for_idf

baseball  economics  politics  Europe  Asia  soccer  war  security  \
0          1          0         1       0     1       1    0         0   
1          0          1         1       1     0       0    0         1   
2          0          0         0       1     1       1    0         0   
3          0          0         1       1     0       0    1         1   
4          0          1         0       0     0       0    0         0   
5          1          0         0       1     0       0    0         0   
6          0          0         0       0     0       0    0         1   
7          0          0         1       1     0       0    1         0   
8          0          0         0       0     0       1    0         0   
9          0          1         0       0     1       0    1         0   
10         0          0         1       0     1       0    0         0   
11         1          0         0       0     0       1    1         0   
12         0          0         1       1     1       0    0         1   
13         0          1         1       1     0       0    0         0   
14         0          0         0       1     0       1    1         1   
15         1          0         0       0     0       1    0         0   
16         0          1         1       1     0       0    0         1   
17         0          0         0       1     0       0    0         0   
18         0          1         1       0     1       0    1         0   
19         0          0         1       1     0       0    1         0   

    shopping  family  
0          0       1  
1          0       0  
2          0       0  
3          0       0  
4          1       1  
5          0       0  
6          0       1  
7          0       1  
8          1       0  
9          0       0  
10         1       0  
11         0       0  
12         0       0  
13         1       0  
14         0       0  
15         1       0  
16         0       0  
17         1       0  
18         0       1  
19         1       0

In [30]:
idf = 1/item_for_idf.sum()
idf

baseball     0.250000
economics    0.166667
politics     0.100000
Europe       0.090909
Asia         0.166667
soccer       0.166667
war          0.142857
security     0.166667
shopping     0.142857
family       0.200000
dtype: float64

In [31]:
item_for_idf = item_w.copy()
item_for_idf

baseball  economics  politics    Europe      Asia    soccer       war  \
0   0.447214   0.000000  0.447214  0.000000  0.447214  0.447214  0.000000   
1   0.000000   0.500000  0.500000  0.500000  0.000000  0.000000  0.000000   
2   0.000000   0.000000  0.000000  0.577350  0.577350  0.577350  0.000000   
3   0.000000   0.000000  0.500000  0.500000  0.000000  0.000000  0.500000   
4   0.000000   0.577350  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.707107   0.000000  0.000000  0.707107  0.000000  0.000000  0.000000   
6   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000   0.000000  0.500000  0.500000  0.000000  0.000000  0.500000   
8   0.000000   0.000000  0.000000  0.000000  0.000000  0.707107  0.000000   
9   0.000000   0.577350  0.000000  0.000000  0.577350  0.000000  0.577350   
10  0.000000   0.000000  0.577350  0.000000  0.577350  0.000000  0.000000   
11  0.577350   0.000000  0.000000  0.000000  0.000000  0.577350  0.577350   
12  0.000000   0.000000  0.500000  0.500000  0.500000  0.000000  0.000000   
13  0.000000   0.500000  0.500000  0.500000  0.000000  0.000000  0.000000   
14  0.000000   0.000000  0.000000  0.500000  0.000000  0.500000  0.500000   
15  0.577350   0.000000  0.000000  0.000000  0.000000  0.577350  0.000000   
16  0.000000   0.500000  0.500000  0.500000  0.000000  0.000000  0.000000   
17  0.000000   0.000000  0.000000  0.707107  0.000000  0.000000  0.000000   
18  0.000000   0.447214  0.447214  0.000000  0.447214  0.000000  0.447214   
19  0.000000   0.000000  0.500000  0.500000  0.000000  0.000000  0.500000   

    security  shopping    family  
0   0.000000  0.000000  0.447214  
1   0.500000  0.000000  0.000000  
2   0.000000  0.000000  0.000000  
3   0.500000  0.000000  0.000000  
4   0.000000  0.577350  0.577350  
5   0.000000  0.000000  0.000000  
6   0.707107  0.000000  0.707107  
7   0.000000  0.000000  0.500000  
8   0.000000  0.707107  0.000000  
9   0.000000  0.000000  0.000000  
10  0.000000  0.577350  0.000000  
11  0.000000  0.000000  0.000000  
12  0.500000  0.000000  0.000000  
13  0.000000  0.500000  0.000000  
14  0.500000  0.000000  0.000000  
15  0.000000  0.577350  0.000000  
16  0.500000  0.000000  0.000000  
17  0.000000  0.707107  0.000000  
18  0.000000  0.000000  0.447214  
19  0.000000  0.500000  0.000000

In [32]:
item_for_idf.values

array([[0.4472136 , 0.        , 0.4472136 , 0.        , 0.4472136 ,
        0.4472136 , 0.        , 0.        , 0.        , 0.4472136 ],
       [0.        , 0.5       , 0.5       , 0.5       , 0.        ,
        0.        , 0.        , 0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.57735027,
        0.57735027, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.5       , 0.        ,
        0.        , 0.5       , 0.5       , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.57735027],
       [0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.70710678],
       [0.        , 0.        , 0.5      

In [33]:
idf.values

array([0.25      , 0.16666667, 0.1       , 0.09090909, 0.16666667,
       0.16666667, 0.14285714, 0.16666667, 0.14285714, 0.2       ])

In [34]:
w_over_idf = item_for_idf.values*idf.values
w_over_idf

array([[0.1118034 , 0.        , 0.04472136, 0.        , 0.0745356 ,
        0.0745356 , 0.        , 0.        , 0.        , 0.08944272],
       [0.        , 0.08333333, 0.05      , 0.04545455, 0.        ,
        0.        , 0.        , 0.08333333, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.05248639, 0.09622504,
        0.09622504, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.05      , 0.04545455, 0.        ,
        0.        , 0.07142857, 0.08333333, 0.        , 0.        ],
       [0.        , 0.09622504, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.08247861, 0.11547005],
       [0.1767767 , 0.        , 0.        , 0.06428243, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.11785113, 0.        , 0.14142136],
       [0.        , 0.        , 0.05     

In [35]:
item_for_idf = pd.DataFrame(data = w_over_idf, columns=keyword)
item_for_idf

baseball  economics  politics    Europe      Asia    soccer       war  \
0   0.111803   0.000000  0.044721  0.000000  0.074536  0.074536  0.000000   
1   0.000000   0.083333  0.050000  0.045455  0.000000  0.000000  0.000000   
2   0.000000   0.000000  0.000000  0.052486  0.096225  0.096225  0.000000   
3   0.000000   0.000000  0.050000  0.045455  0.000000  0.000000  0.071429   
4   0.000000   0.096225  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.176777   0.000000  0.000000  0.064282  0.000000  0.000000  0.000000   
6   0.000000   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000   0.000000  0.050000  0.045455  0.000000  0.000000  0.071429   
8   0.000000   0.000000  0.000000  0.000000  0.000000  0.117851  0.000000   
9   0.000000   0.096225  0.000000  0.000000  0.096225  0.000000  0.082479   
10  0.000000   0.000000  0.057735  0.000000  0.096225  0.000000  0.000000   
11  0.144338   0.000000  0.000000  0.000000  0.000000  0.096225  0.082479   
12  0.000000   0.000000  0.050000  0.045455  0.083333  0.000000  0.000000   
13  0.000000   0.083333  0.050000  0.045455  0.000000  0.000000  0.000000   
14  0.000000   0.000000  0.000000  0.045455  0.000000  0.083333  0.071429   
15  0.144338   0.000000  0.000000  0.000000  0.000000  0.096225  0.000000   
16  0.000000   0.083333  0.050000  0.045455  0.000000  0.000000  0.000000   
17  0.000000   0.000000  0.000000  0.064282  0.000000  0.000000  0.000000   
18  0.000000   0.074536  0.044721  0.000000  0.074536  0.000000  0.063888   
19  0.000000   0.000000  0.050000  0.045455  0.000000  0.000000  0.071429   

    security  shopping    family  
0   0.000000  0.000000  0.089443  
1   0.083333  0.000000  0.000000  
2   0.000000  0.000000  0.000000  
3   0.083333  0.000000  0.000000  
4   0.000000  0.082479  0.115470  
5   0.000000  0.000000  0.000000  
6   0.117851  0.000000  0.141421  
7   0.000000  0.000000  0.100000  
8   0.000000  0.101015  0.000000  
9   0.000000  0.000000  0.000000  
10  0.000000  0.082479  0.000000  
11  0.000000  0.000000  0.000000  
12  0.083333  0.000000  0.000000  
13  0.000000  0.071429  0.000000  
14  0.083333  0.000000  0.000000  
15  0.000000  0.082479  0.000000  
16  0.083333  0.000000  0.000000  
17  0.000000  0.101015  0.000000  
18  0.000000  0.000000  0.089443  
19  0.000000  0.071429  0.000000

In [36]:
users_pro_idf = pd.DataFrame(index=[0,1], columns=items_col)
users_pro_idf['Unnamed: 0'] = ['User 1', 'User 2']
users_pro_idf

Unnamed: 0 baseball economics politics Europe Asia soccer  war security  \
0     User 1      NaN       NaN      NaN    NaN  NaN    NaN  NaN      NaN   
1     User 2      NaN       NaN      NaN    NaN  NaN    NaN  NaN      NaN   

  shopping family  
0      NaN    NaN  
1      NaN    NaN

In [37]:
keyword = items_col[1:]
for i in keyword:
    tmp_list = list()
    tmp_list.append(np.nansum(np.array(item_for_idf[i])*np.array(users['User 1'])))
    tmp_list.append(np.nansum(np.array(item_for_idf[i])*np.array(users['User 2'])))
    users_pro_idf[i] = tmp_list

In [38]:
users_pro_idf

Unnamed: 0  baseball  economics  politics    Europe      Asia    soccer  \
0     User 1  0.432918  -0.157869 -0.050000  0.018828  0.000000  0.170761   
1     User 2 -0.256141   0.166667  0.105279  0.136364 -0.074536 -0.170761   

        war  security  shopping    family  
0 -0.063888 -0.083333  0.082479  0.000000  
1 -0.011050  0.250000  0.000000 -0.089443

In [39]:
users_doc_pro_idf = pd.DataFrame(index=range(0,20), columns=['User 1', 'User 2'])
users_doc_pro_idf

User 1 User 2
0     NaN    NaN
1     NaN    NaN
2     NaN    NaN
3     NaN    NaN
4     NaN    NaN
5     NaN    NaN
6     NaN    NaN
7     NaN    NaN
8     NaN    NaN
9     NaN    NaN
10    NaN    NaN
11    NaN    NaN
12    NaN    NaN
13    NaN    NaN
14    NaN    NaN
15    NaN    NaN
16    NaN    NaN
17    NaN    NaN
18    NaN    NaN
19    NaN    NaN

In [40]:
users_doc_pro_idf['User 1'] = np.dot(item_for_idf[keyword], users_pro_idf[keyword][0:1].values[0])
users_doc_pro_idf['User 2'] = np.dot(item_for_idf[keyword], users_pro_idf[keyword][1:2].values[0])
users_doc_pro_idf['docs'] = users['Unnamed: 0']

In [41]:
users_doc_pro_idf

User 1    User 2   docs
0   0.058893 -0.050213   doc1
1  -0.021744  0.046185   doc2
2   0.017420 -0.016446   doc3
3  -0.013152  0.031506   doc4
4  -0.008388  0.005710   doc5
5   0.077740 -0.036514   doc6
6  -0.009821  0.016814   doc7
7  -0.006208  0.001729   doc8
8   0.028456 -0.020124   doc9
9  -0.020460  0.007954  doc10
10  0.003916 -0.001094  doc11
11  0.073648 -0.054314  doc12
12 -0.008589  0.026084  doc13
13 -0.008909  0.025351  doc14
14  0.003578  0.012012  doc15
15  0.085720 -0.053402  doc16
16 -0.021744  0.046185  doc17
17  0.009542  0.008766  doc18
18 -0.018085  0.002869  doc19
19 -0.000316  0.010673  doc20

In [42]:
## 비교를 위한 2번 문제의 결과 호출
users_doc_pro_w.sort_values(by=['User 1'], ascending=False)[:5]

User 1    User 2   docs
15  1.924646 -1.183064  doc16
5   1.370923  0.336184   doc6
11  1.333114 -1.227723  doc12
8   1.132724 -0.724476   doc9
0   1.009019 -0.845577   doc1

In [43]:
users_doc_pro_idf.sort_values(by=['User 1'], ascending=False)[:5]

User 1    User 2   docs
15  0.085720 -0.053402  doc16
5   0.077740 -0.036514   doc6
11  0.073648 -0.054314  doc12
0   0.058893 -0.050213   doc1
8   0.028456 -0.020124   doc9

In [44]:
users_doc_pro_w.iloc[[0,8],[0,2]]

User 1  docs
0  1.009019  doc1
8  1.132724  doc9

In [45]:
users_doc_pro_idf.iloc[[0,8],[0,2]]

User 1  docs
0  0.058893  doc1
8  0.028456  doc9

In [46]:
users_doc_pro_w.iloc[[5],[1,2]]

User 2  docs
5  0.336184  doc6

In [47]:
users_doc_pro_idf.iloc[[5],[1,2]]

User 2  docs
5 -0.036514  doc6